language: perl
before_install:
  - sudo apt-get install -qq nmap
script: ./travis-ci-build.sh
perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
notifications:
  email: false
# whitelist
branches:
  only:
    - master
    - 2.3.x
