sudo: false
language: perl
perl:
# Stuffs need to be backported from 2.3.x about SSL support before enabling perl 5.20 & 5.22
#  - "5.22"
#  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
notifications:
  email: false
# whitelist
branches:
  only:
    - master
    - 2.3.x
    - 2.3.x-travis-test
