sudo: false
language: perl
# list available perl version
before_install:
  - perlbrew list
  - perl -V
perl:
#  - "5.28"                 # still not available version
#  - "5.28-shrplib"         # still not available version
  - "5.26"
  - "5.26-shrplib"
  - "5.24"
  - "5.24-shrplib"
  - "5.22"
  - "5.22-shrplib"
  - "5.20"
#  - "5.20-shrplib"         # cpanm failure
  - "5.18"
#  - "5.18-shrplib"         # cpanm failure
  - "5.16"
#  - "5.16-shrplib"         # cpanm failure
  - "5.14"
  - "5.12"
  - "5.10"
#  - "5.8"
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
# whitelist
branches:
  only:
    - 2.4.x
    - 2.4.x-travis-test
