sudo: false
language: perl
# list available perl version
before_install:
  - perlbrew list
  - perl -V
perl:
  - "5.22-thr"
  - "5.20-thr"
  - "5.18-thr"
  - "5.16-thr"
  - "5.14-thr"
  - "5.12-thr"
  - "5.10-thr"
  - "5.8-thr"
notifications:
  email: false
# whitelist
branches:
  only:
    - master
    - 2.3.x
    - 2.3.x-travis-test
