sudo: false
language: perl
# list available perl version
before_install:
  - perlbrew list
  - perl -V
perl:
  - "5.25.1-thr"
  - "5.22.0-thr"
  - "5.20.1-thr"
  - "5.18.3-thr"
  - "5.16.3-thr"
  - "5.14.4-thr"
  - "5.12.5-thr"
  - "5.10.1-thr"
  - "5.8.9-thr"
notifications:
  email: false
# whitelist
branches:
  only:
    - master
    - 2.3.x
    - 2.3.x-travis-test
