language: perl
script: ./travis-ci-build.sh
perl:
  - "5.22"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
notifications:
  email: false
# whitelist
branches:
  only:
    - master
    - 2.3.x
