sudo: false
language: perl
perl:
  - "5.32"
  - "5.32-shrplib"
  - "5.30"
  - "5.30-shrplib"
  - "5.28"
  - "5.28-shrplib"
  - "5.26"
#  - "5.26-shrplib"
  - "5.24"
#  - "5.24-shrplib"
  - "5.22"
  - "5.22-shrplib"
  - "5.20"
  - "5.20-shrplib"         # cpanm failure
  - "5.18"
  - "5.18-shrplib"         # cpanm failure
  - "5.16"
  - "5.16-shrplib"         # cpanm failure
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
# whitelist
branches:
  only:
    - develop
