branches:
  only:
    - develop

skip_tags: true
shallow_clone: true

platform:
  - x86
  - x64

skip_commits:
  files:
    - '**/*.md'
    - 'contrib/*/*'

install:
  - cinst strawberryperl --version 5.28.2.1
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - echo %cd%
  - cpan -T Module::Install
  - cpanm --notest --installdeps .
  - cpanm --notest Compress::Zlib IO::Socket::SSL LWP::Protocol::https
  - cpanm --notest Win32::Daemon Win32::Unicode::File
  - cpanm --notest Parse::EDID DateTime
  - cpanm --notest Archive::Extract Digest::SHA File::Copy::Recursive
  - cpanm --notest JSON::PP URI::Escape Net::Ping Parallel::ForkManager

build_script:
  - perl Makefile.PL
  - dmake

test_script:
  - dmake test
