branches:
  only:
    - 2.4.x

notifications:
  - provider: Webhook
    url: https://hooks.aethonan.pro/appveyor/388950989/

skip_tags: true
shallow_clone: true

# Build matrix, ref: https://www.appveyor.com/docs/build-environment/
# As of 2017/11:
#  'Visual Studio 2015' selects 'Windows Server 2012 R2' based worker
#  'Visual Studio 2017' selects 'Windows Server 2016'    based worker
image:
- Visual Studio 2015
- Visual Studio 2017

platform:
  - x86
  - x64

install:
  - cinst strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - echo %cd%
  - cpan Module::Install
  - cpanm -f --verbose --notest --installdeps .
  - cpanm -f --verbose --notest Compress::Zlib IO::Socket::SSL LWP::Protocol::https
  - cpanm -f --verbose --notest Win32::Daemon Win32::Unicode::File
  - cpanm -f --verbose --notest Parse::EDID DateTime
  - cpanm -f --verbose --notest Archive::Extract Digest::SHA File::Copy::Recursive
  - cpanm -f --verbose --notest JSON::PP URI::Escape Net::Ping Parallel::ForkManager

build_script:
  - perl Makefile.PL
  - dmake

test_script:
  - dmake test
