version: 2

general:
  branches:
    only:
      - develop

jobs:
  build:
    macos:
      xcode: "12.1.0"

    steps:
     - checkout
     - run:
         name: Install cpanminus
         command: |
           perl --version
           curl -L https://cpanmin.us | perl - App::cpanminus
           $HOME/perl5/bin/cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
           echo 'export PERL5LIB="$HOME/perl5/lib/perl5"' >> $BASH_ENV
     - run:
         name: Install deps
         command: |
           echo $PERL5LIB
           $HOME/perl5/bin/cpanm -L ~/perl5 Module::Install
           touch Makefile.PL
           $HOME/perl5/bin/cpanm -L ~/perl5 --installdeps --verbose --notest .
     - run: perl Makefile.PL
     - run: make
     - run: make test
